### ISSUE TITLE
Economia da feira

### ISSUE THREAD

**Issue by boidacarapreta** [feira-de-jogos/economia#1]
Documentar como será a economia da feira de jogos baseada em moeda virtual: o progresso dos jogos Web é o crédito, enquanto que os [equipamentos](https://github.com/feira-de-jogos/equipamentos/issues/1) será de débito.

**Comment by henriquecmh** [comment]
Fiz alguns levantamentos, no entanto seria interessantes estabelecer (definir) alguns critérios: qual o BD utilizado, visto que a integração do hardware com a nuvem será realizada via MQTT (arduino) ou diretamente via rasp? Enviaremos string ou valor numerico diretamente? a validação da conta será realizada externamente (google, facebook, instagram, pinterest, etc...) ou teremos dados locais dos usuários (e-mail e senha criados)?

Estabelecendo-se alguns critérios se torna mais fácil avaliar qual seria a melhor forma de configuração e de seleção de alguns hardwares (lembrando dos problemas do semestre anterior).

**Comment by boidacarapreta** [comment]
O acesso será via MQTT para atender diretamente os terminais microcontrolados.

**Comment by boidacarapreta** [comment]
A troca de dados será via _string_. O tratamento dos dados será feita no serviço em nuvem.

**Comment by boidacarapreta** [comment]
Será possível validar o usuário tanto via email com autenticação externa (para facilitar aplicação Web) e par usuário + senha.

**Comment by boidacarapreta** [comment]
Todas essas dúvidas eu tentei atender nos [requisitos de serviços de nuvem](https://github.com/feira-de-jogos/nuvem/issues/1).
